### ISSUE TITLE
[Suggestion]: Mutant Enderman Tweaks

### ISSUE THREAD

**Issue by FietDit** [Fuzss/mutantmonsters#1]
### Suggestion (Required)

so there is a little suggestion about mutant enderman

the first suggesiton is that the mutant enderman will only use 4 arms when they are in a battle/fight, they will only have 2 arms if there is no enemy around them
![2023-04-21_04 32 54](https://user-images.githubusercontent.com/109415226/233495288-a2fe54c3-1aaa-415e-b4ff-201b36da3f7b.png)

and the second suggestion is to fix the position of mutant enderman forearms
![2023-04-21_04 38 55](https://user-images.githubusercontent.com/109415226/233495369-f3c1dc81-ee4e-40f2-844f-9e58cc6757f5.png)

(these suggestions are meant to make it more original like OG mutant mobs)

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
