### ISSUE TITLE
[Suggestion]: Update mutant zombie's and mutant skeleton's head textures

### ISSUE THREAD

**Issue by Chachavo** [Fuzss/mutantmonsters#10]
### Suggestion (Required)

The original mutant zombie's and mutant skeleton's textures were custom but the head textures were copied and pasted into them. Now that minecraft has new textures their heads no longer match their normal counterparts.
They also look kinda nice
This is what they would look like with the updated textures (more notable on mutant skeleton).
![2023-05-18_00 21 53](https://github.com/Fuzss/mutantmonsters/assets/131740687/72dc012e-29e4-4326-bf70-11fabbf26449)

**Comment by Chachavo** [comment]
I found a texture pack for mutant beassts called Mutant Beasts: The Retexturing
Which updates all textures to the new style. So maybe you could talk to the creator to implement those textures in the mod.
Aswell as perhaps having the old textures in a resourcepack that comes with the mod (similar to how minecraft has the programmers art texture pack).
It's just a suggestion.

**Comment by Fuzss** [comment]
I shot they creator of Mutant Beasts: The Retexturing a message on Curse, I'll keep this issue updated.

**Comment by Fuzss** [comment]
New texture have been added in v8.0.1.
