### ISSUE TITLE
[Bug]: Using a nametag on a mutant zombie gives the Burn Zombie Burn advancement

### ISSUE THREAD

**Issue by Chachavo** [Fuzss/mutantmonsters#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

As the title says, using a nametag on the mutant zombie grants the "Burn Zombie Burn" advancement for burning it by using flint and steel or a fire charge.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
