### ISSUE TITLE
[Suggestion]: Make results from using Chemical X configurable

### ISSUE THREAD

**Issue by Yellowbross** [Fuzss/mutantmonsters#12]
### Suggestion (Required)

https://legacy.curseforge.com/minecraft/mc-mods/mutant-beasts/issues/66

bringing back a suggestion other people made for Mutant Beasts that unfortunately didn't make it in before the mod died (despite chumbanotz showing interest in the idea), it'd be great to have an option in the config file to choose what mobs will turn into what mutant when chemical X is thrown onto them. this would be especially helpful in being able to connect the original Mutant Creatures to its fanmade spinoff mods, such as Mutant More: for example, throwing chemical X onto a blaze to create Mutant More's mutant blaze

as a safeguard, if a mod entity's name ends up reading as null, trying to mutate the mob would simply fail and cause the mob to explode like any other unmutatable mob

i'd imagine the config option would be a list that looks something like this:
["minecraft:zombie;mutantmonsters:mutant_zombie",
"minecraft:skeleton;mutantmonsters:mutant_skeleton",
"minecraft:creeper;mutantmonsters:mutant_creeper",
"minecraft:enderman;mutantmonsters:mutant_enderman",
"minecraft:snow_golem;mutantmonsters:mutant_snow_golem"]

**Comment by Fuzss** [comment]
Thanks for the suggestion! Added in v4.0.2.
