### ISSUE TITLE
[Bug]: Chemical X not working on snow golems

### ISSUE THREAD

**Issue by Chachavo** [Fuzss/mutantmonsters#13]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.4

### Notes (Required)

Chemical X is not able to turn snow golems into mutant snow golems, can also be noted that if thrown into a mutant snow golem it will be affected, which indicates that the mod is not considering it as a result from a mutation.
Tried deleting and re adding the snow golem - mutant snow golem config, as well as deleting the config file and re launching the game. None worked.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in latest version.
