### ISSUE TITLE
[Crash]: 1.18.2 tropicraft crash

### ISSUE THREAD

**Issue by asweqr** [Fuzss/mutantmonsters#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.0.0

### Notes (Required)

1 start minecraft
2 click create new world
3 confirm create new world
4 game crashes

### Crash Report (Required)

https://gist.github.com/asweqr/26fe9bbdd79ffa9d1fb53ce268d1b2fa

### latest.log (Optional)

https://gist.github.com/asweqr/92a2530d62fdbcbccb7923fedf6789a3

**Comment by Fuzss** [comment]
Fixed in latest version of Puzzles Lib, thanks for reporting!
