### ISSUE TITLE
Mutant skeleton's arrow crash if colliding with elder copper golem[Crash]: 

### ISSUE THREAD

**Issue by KaratFeng** [Fuzss/mutantmonsters#20]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

[FABRIC] [1.19.2] MutantMonsters-v4.0.6

### Notes (Required)

1.mutant skeleton shoot the elder copper golem from https://www.curseforge.com/minecraft/mc-mods/beneath-the-wetlands
2.crash

### Crash Report (Required)

https://gist.github.com/KaratFeng/252662bcf3c12f6eecdf18d35557a894

**Comment by Fuzss** [comment]
There code isn't publicly available, I can't look into it unfortunately. Please report the issue to their issue tracker.
