### ISSUE TITLE
[Suggestion]: Mutants should be able to break leaves similar to the Ravager

### ISSUE THREAD

**Issue by Slimation** [Fuzss/mutantmonsters#21]
### Suggestion (Required)

To make it easier for the mobs to path find to the player, Mutants should be able to break blocks such as leaves similar to the way the Ravager does.

**Comment by Fuzss** [comment]
Added in v8.0.5, thanks for the suggestion! To prevent mutants from destroying forests at night, they will only break leaves when actively trying to reach a target, and not when simply strolling about.
