### ISSUE TITLE
[Bug]: Mutant snow golems turn waterlogged half slabs into ice

### ISSUE THREAD

**Issue by Pankine** [Fuzss/mutantmonsters#22]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.2

### Notes (Required)

Expected behavior: mutant snow golems should cover the waterlogged half slab in snow like how it does with double slabs, blocks, and unwaterlogged half slabs
Current behavior: mutant snow golems turn waterlogged half slabs into ice not acknowledging the slab's existence

**Comment by Fuzss** [comment]
Fixed in v8.0.5 for 1.20.1. 1.19.4 is no longer supported unfortunately.
