### ISSUE TITLE
[Crash]: Error loading mod 

### ISSUE THREAD

**Issue by Nouser12** [Fuzss/mutantmonsters#24]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.2

### Notes (Required)

1. Open Minecraft Launcher
2. Launch Game with Forge 1.19.4-forge-45.1.0
3. Error loading mod occurs.

[crash-2023-06-29_11.12.27-fml.txt](https://github.com/Fuzss/mutantmonsters/files/11904004/crash-2023-06-29_11.12.27-fml.txt)

Note: Sometimes the mod would load without issues after a couple of restarts. But at the moment I've had like 10 failed restarts in a row.

### Crash Report (Required)

https://gist.github.com/Nouser12/29a59c97c6c76f0c411e0181cc5e05aa

### latest.log (Optional)

https://gist.github.com/Nouser12/0d412c47bdd67808ad4983dc4ba33479

**Comment by Fuzss** [comment]
Thanks for reporting! The issue has been fixed for the latest 1.20.1 release of Puzzles Lib. 1.19.4 is no longer supported.
