### ISSUE TITLE
[Crash]: Weird crash when rendering Mutant Enderman (Seemingly while teleporting)

### ISSUE THREAD

**Issue by TheAGamePlayer** [Fuzss/mutantmonsters#25]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

While testing my datapack addon to add Mutant Monsters as an invasion for my Pure Suffering Mod, it would seem that a rendering bug would occasionally happen with Mutant Enderman causing the game to crash. At first I expected Pure Suffering's HyperCharge render layer to be the culprit as it applies it to any mob featured in an Invasion, however I was able to recreate the crash without Pure Suffering involved at all.

Steps to Recreate Crash:
1. Create an Observer clock on a dispenser facing upwards.
2. Make an area that'll trap Mutant Enderman above the dispenser.
3. Fill the dispenser with Mutant Enderman spawn eggs.
4. Watch as entity cramming causes Mutant Enderman to teleport.
5. Wait until you crash from a Mutant Enderman teleporting (Took me roughly 10 minutes to finally crash from this happening).

### Crash Report (Required)

https://gist.github.com/TheAGamePlayer/c8c2d98c01cdfd91c8aae7102d3dbfb0

### latest.log (Optional)

https://gist.github.com/TheAGamePlayer/8fd1834a351911f0cceabf3e70f7b062

**Comment by Fuzss** [comment]
Fixed in v8.0.1.
