### ISSUE TITLE
[Suggestion]: Increasing spawn chances per passed ingame day

### ISSUE THREAD

**Issue by night2078** [Fuzss/mutantmonsters#26]
### Suggestion (Required)

Hey! I got a nice suggestion.

_**Background:**_

I love to have the challenge of super powerful monsters in my world, especially since i locked my world to the normal difficulty. BUT, i ran into an small issue the other day. I'm using this mod along a bunch of other mods, including LevelZ. Since i just started the world, i only had 3 hearts and unfortunately a mutant skeleton did spawn near my bed. Since the mutant does not burn during daytime, i kinda got softlocked since the skeleton just killed me over and over (which frustated me a bit ngl). So, i came up with a neat idea.

_**The suggestion:**_

Meaby, it would be a nice idea to have the option to let the spawn rate increase with the day count of your world. Of course completely optional and configurable, but in my case, it would be good to set the chance to zero for the first days and then let it slowly increase by 0.01 every 7 days for example.

Config options could potentially be:
- starting chance
- how many days till the first increament
- how many % increament
- how many days for each increament (like every day or every 3 days, you get the idea)
- and a maximum % that it can increase to

This way, it would allow players to tweak the mod to their liking. Prevent frustration in the early game and have a challenge in the late game, when more mutants spawn.

**Comment by Fuzss** [comment]
I'd rather leave that to other mods altering spawning mechanics in such a way.
