### ISSUE TITLE
[Bug]: End Portal blocks in the end can be replaced by blocks when an end soul hand throws a block at the bedrock portal frame.

### ISSUE THREAD

**Issue by TheAGamePlayer** [Fuzss/mutantmonsters#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

Steps to reproduce:
1) Go to the end & beat the dragon.
2) Get an end soul hand & grab an end stone block.
3) Go to the bedrock portal and throw the end stone block at the bedrock where an end portal block is. This should replace the block, but sometimes it requires different throwing angles to work.

**Comment by Aceplante2** [comment]
This applies to almost all non full blocks that I can tell. campfires, brewing stands, beds etc

**Comment by Fuzss** [comment]
Fixed in v8.0.5.
