### ISSUE TITLE
[Bug]: Mutant Zombie Issues

### ISSUE THREAD

**Issue by FietDit** [Fuzss/mutantmonsters#28]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

1. Mutant Zombie has rough arms transition when dying animation is playing
2. an old issue since the Mutant Creatures has started, maybe you can fix it, Mutant Zombie legs doesn't touch the ground, it will only when they are walking.

https://github.com/Fuzss/mutantmonsters/assets/109415226/66cb8a5f-301e-4473-8d07-18cd5a864274

**Comment by Fuzss** [comment]
Offset is fixed in v8.0.3. Transition won't be fixed.
