### ISSUE TITLE
[Bug]: Mutant Enderman Arms bug

### ISSUE THREAD

**Issue by FietDit** [Fuzss/mutantmonsters#29]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

When mutant enderman is angry, it will eventually pulling out their hidden arms, the issue is, both of the hidden arms doesn't connected to each limb
![2023-07-09_17 46 06](https://github.com/Fuzss/mutantmonsters/assets/109415226/df95fcdd-d5dc-448e-9897-d4bca76e852c)

**Comment by Fuzss** [comment]
Won't fix.
