### ISSUE TITLE
[Bug]: Mutant Skeleton Armor provides buffs when in inventory, not just when worn

### ISSUE THREAD

**Issue by dabomb6405** [Fuzss/mutantmonsters#3]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

As the title says, you don't have to wear Mutant Skeleton Armor to receive the buffs. At the moment, you get the buffs as long as the armor is in your inventory.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
