### ISSUE TITLE
[Bug]: Config continues to reload

### ISSUE THREAD

**Issue by thedeerirty** [Fuzss/mutantmonsters#32]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.6

### Notes (Required)

I'm not entirely sure this is a bug, but my server console is consistently sent spam from this mod, it states it keeps reloading the configuration? Like, repeatedly. I went and check my files, and no altercations seemed to be present, no sudden backup files, and I've never edited the file myself. 

It also seems to happen at irregular times, often when simply no one is on, or when people are just doing something simple, say farming.
![image](https://github.com/Fuzss/mutantmonsters/assets/58305182/e108ae05-1faa-4ebd-9ddc-80c57f4d8d0d)

**Comment by Fuzss** [comment]
That's not really in my hands, the config system sometimes does that on certain (file) systems. It's best to delete the config file manually and hope the issue doesn't arise again when it is generated again.

This should probably be reported to Forge as they did design the config system (it's a 1:1 port on Fabric), but you probably won't get far there considering that this happened on Fabric...
