### ISSUE TITLE
[Crash]: Crash in start up

### ISSUE THREAD

**Issue by SuperStefan97** [Fuzss/mutantmonsters#33]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

MutantMonsters-v8.0.2-1.20.1-Forge

### Notes (Required)

1. Install MutantMonsters-v8.0.2-1.20.1-Forge and PuzzlesLib-v8.0.11-1.20.1-Forge
2. Start game with official Minecraft Launcher
3. Crashes

### Crash Report (Required)

https://gist.github.com/SuperStefan97/16ef7b4feca001e17f8670b7e582fdea

**Comment by Fuzss** [comment]
Thank you, fixed in Puzzles Lib v8.0.12.
