### ISSUE TITLE
[Bug]: More Mutant Enderman And Mutant Skeleton Spawns Than There Should Be

### ISSUE THREAD

**Issue by MysticWolfy** [Fuzss/mutantmonsters#36]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

[FABRIC] [1.20.1] MutantMonsters-v8.0.2

### Notes (Required)

The bug is that in the Nether, Mutant Endermen and Mutant Skeletons spawn a lot more than they should. The config is set to 0.05, however the Mutant Endermen and Mutant Skeletons are spawning a lot more. There are more Mutant Endermen and Mutant Skeletons than their vanilla variants.

To recreate this you need to

1. Create a new world with the default config settings
2. Go to the nether and find a warped forest biome
3. Wait about a minute
4. Kill all mutant endermen. The number will be higher than it should be.

**Comment by Fuzss** [comment]
Fixed in v8.0.3.
