### ISSUE TITLE
[Bug]: Mutant Monsters Config Doesn't Change Anything

### ISSUE THREAD

**Issue by MysticWolfy** [Fuzss/mutantmonsters#37]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

[FABRIC] [1.20.1] MutantMonsters-v8.0.2

### Notes (Required)

When the config is set to default, in the nether, there are a lot of mutant enderman and skeletons. If the config is changed to have zero spawns of mutants, it does not change. The first screenshot is with the config at default, and the second is with the config chance set to zero.

To Recreate:

1. Create a new world using the default config and go to the nether and find a warped forest.
2. Kill all mutant endermen to see how many there are.
3. Close the game and set config to zero
4. Re-open the game and kill all mobs
5. Wait about a minute and kill all mutant enderman.
6. The numbers will not be as different as they should be.

![image](https://github.com/Fuzss/mutantmonsters/assets/123000065/4ac4290c-67d4-4647-a82c-1d2ce98ec101)

![image](https://github.com/Fuzss/mutantmonsters/assets/123000065/2421a1a2-42b9-4392-8de6-d0941a873e10)

**Comment by Fuzss** [comment]
The config does work, especially when set to `0.0`, just tried it extensively. You need to relog for changes to apply though, maybe that was the issue here. The rest is concerning #36 which has been fixed now.
