### ISSUE TITLE
[Bug]: Mutant Zombie Dissappear and Chemical X recipe

### ISSUE THREAD

**Issue by kriskooz** [Fuzss/mutantmonsters#38]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.0.1

### Notes (Required)

Hello,
during my gameplay I encountered Mutant Zombie and killed him using bow with Flame. Monster slowly disappeared, but then it became completely invisible and started hitting me. Unfortunately I don't have any pic or vid.

Second issue:
There is no recipe for Chemical X. It can be only obtained in Creative Mode.
Regards, Chris.

**Comment by Fuzss** [comment]
The zombie thing is a desync issue, not much I can do about it.
The Chemical X recipe is a brewing recipe with any of the mutant's drops, JEI has trouble showing these sometimes, REI always works.
