### ISSUE TITLE
[Bug]: Hulk Hammer shockwave starts away from player

### ISSUE THREAD

**Issue by dabomb6405** [Fuzss/mutantmonsters#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

The shockwave ability on the hulk hammer starts a few blocks in front of the player instead of directly in front of them.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
