### ISSUE TITLE
[Crash]: Chemical X splash on zombie crashes

### ISSUE THREAD

**Issue by peachpotato** [Fuzss/mutantmonsters#40]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

MutantMonsters-v3.0.1-1.18.2-Forge

### Notes (Required)

1.summon 15-20 zombies surrounded by fences
2.throw Chemical X splash to the zombies 
3.game crashed

### Crash Report (Required)

https://gist.github.com/peachpotato/04c179170210eff4b1ff7f3e78cd0378

**Comment by Fuzss** [comment]
Try without the dimensionviewer mod.

**Comment by Fuzss** [comment]
This is issue is solved by updating Forge to the latest version.
