### ISSUE TITLE
[Crash]: Mutant Enderman Client Crash

### ISSUE THREAD

**Issue by Mikeatron-User** [Fuzss/mutantmonsters#44]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.3

### Notes (Required)

1. Spawn Mutant Enderman
2. Let it fight mobs until it dies
3. During death animation, this crash occured.

### Crash Report (Required)

https://gist.github.com/Mikeatron-User/2a11b5e09eecce26cf223a2d9e56965c

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.4.
