### ISSUE TITLE
[Suggestion]: Mutant Zombie & Skeleton should rarely spawn wearing Carved Pumpkins or Jack o' Lanterns on Halloween

### ISSUE THREAD

**Issue by Yellowbross** [Fuzss/mutantmonsters#45]
### Suggestion (Required)

On Halloween, the original counterparts of the Mutant Zombie and Mutant Skeleton have a rare chance to spawn wearing a Carved Pumpkin or a Jack o' Lantern. Adding this to the mutants wouldn't add very much to the mod, but it'd be a nice small QoL feature that'd add slightly more parity between the undead mutants and their vanilla counterparts.

![image](https://github.com/Fuzss/mutantmonsters/assets/85346124/609d200f-4cba-4ba0-9a50-8b6767b5dcb6)
![image](https://github.com/Fuzss/mutantmonsters/assets/85346124/412b3dcc-a402-4dc0-9bca-b902f9264b83)

**Comment by Fuzss** [comment]
Thanks for this suggestion, this is not planned.
