### ISSUE TITLE
[Bug]: Mutant Zombie health resets to normal after re-spawn with RPG Difficulty Mod

### ISSUE THREAD

**Issue by douglasg14b** [Fuzss/mutantmonsters#47]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

The mutant zombie has it's health scaled by the [RPG Difficulty](https://github.com/Globox1997/RpgDifficulty/tree/1.20) mod. However, when the zombie is killed after the first time, it's health resets to the mod's default value when it respawns. Instead of using the scaled health.

### Scaled: 
![image](https://github.com/Fuzss/mutantmonsters/assets/1400380/050e069f-d3b3-4cbb-b2df-ce86c8b97148)

### After Respawn

![image](https://github.com/Fuzss/mutantmonsters/assets/1400380/0ef53e07-4ae3-425c-9666-95a6b3d95591)

### Sometimes the max health is way off

![image](https://github.com/Fuzss/mutantmonsters/assets/1400380/a6bbb664-c6a8-40de-bc9e-c26a6720525b)

cc https://github.com/Globox1997/RpgDifficulty/issues/68

**Comment by Fuzss** [comment]
When setting the health for respawning, the mutant zombie uses the value returned by LivingEntity::getMaxHealth and scales that. RPGDifficulty should make sure that the new max health it sets is also returned by that method.
