### ISSUE TITLE
[Crash]: Mutant Enderman crashed Clientside

### ISSUE THREAD

**Issue by VenaticTea395** [Fuzss/mutantmonsters#49]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.3

### Notes (Required)

1. Find a mutant enderman.
2. Kill it and stay away or get hit by the self-destruction phase (or just the final phase before it is completely died).
3. Clientside get crashed immediately.

I don't know what exactly is the issue from the final phase of the mutant enderman, but I believe too much things (e.g. fireworks, souls, etc) shoot out....

However, currently to play the game with being crashed there is a mod can handle it called Neruina. https://www.curseforge.com/minecraft/mc-mods/neruina/
despite can be handled by mods but I hope you can find the actual issue and fix it.

### Crash Report (Required)

https://gist.github.com/VenaticTea395/5e425bba15b13c49da053a4aec7439c6

**Comment by Fuzss** [comment]
Thanks for reporting! Please make sure you are using the latest version of Mutant Monsters.
