### ISSUE TITLE
[Crash]: Mutant Zombie's throw attack crashed the game

### ISSUE THREAD

**Issue by Yellowbross** [Fuzss/mutantmonsters#50]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.4

### Notes (Required)

Playing on 1.20.1, using the NeoForged modloader, I decided to make the Mutant Zombie fight the Mutant Skeleton. Upon Mutant Zombie using its throw attack to finish off the Mutant Skeleton, the game crashed. I also remember this happening back on 1.16 in Mutant Beasts with another mob; my guess is that the Mutant Zombie's throw attack will crash the game if a mob instantly despawns as it's being killed by the slam downward.

To reproduce (this one is kind of tricky to reproduce, since the random chance needs to align correctly):
1. Make Mutant Zombie and Mutant Skeleton fight
2. Make sure Mutant Skeleton is on low enough HP, and that the Mutant Zombie will use the throw attack to kill Mutant Skeleton
3. The game crashes

### Crash Report (Required)

https://pastebin.com/juMSzcw6

**Comment by Fuzss** [comment]
Fixed in v8.0.5.
