### ISSUE TITLE
Mutant zombie wayyy too common

### ISSUE THREAD

**Issue by Aceplante2** [Fuzss/mutantmonsters#52]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

1.18.2

### Notes (Required)

Please add a config file where I can specify a cap of 1 at any given time.

**Comment by Fuzss** [comment]
That‘s not how spawning works, there cannot be an absolute cap. Set the existing spawn chance config option as low as possible.

**Comment by Aceplante2** [comment]
Ive heard that some mods have a custom category for their mobs/bosses. I think it would make sense for yours to, and not be considered regular hostile mobs

**Comment by Fuzss** [comment]
Hmm, that‘s actually an interesting idea…

**Comment by Fuzss** [comment]
Fixed in v8.0.5. Will probably backport to 1.18.2 at some point.
