### ISSUE TITLE
[Suggestion]: add a config???

### ISSUE THREAD

**Issue by fourthhouse** [Fuzss/mutantmonsters#53]
### Suggestion (Required)

The config file only lets you edit spawn weights. I wish I could also make the mobs more powerful like adding damage in the config and health. More importantly there are issues with this mod when combined with other mods. Like mob grinding utils adds dirt that makes these mobs spawn every second or so, suddenly i have 600 skeleton bone entities in one chunk and my tps is under 15.. spark report says the skeleton bones making more lag than all other 450 mods combined. I've also noticed players using such autofarms to have tons and tons of creeper minions, which take as much tps each as 5 villagers. So i would love to have the following config options added if possible: limit mutant skeleton bones per chunk, limit creeper minions per chunk or player, modify mutant damage and health. 
thanks
Edit: not blaming this mod for lag, just suggesting improvement for optimization! thanks for upkeeping this mod 
![Screenshot 2023-10-18 012455](https://github.com/Fuzss/mutantmonsters/assets/56618632/29f9068c-cb3e-4b11-828d-9a409a44a8cf)

**Comment by Fuzss** [comment]
v8.0.5 introduces a hard-cap for entities dropped by some mutants, like skeleton parts and the creeper egg. This means after a certain amount of those entities is reached no new ones will spawn when more mutants die.

Damage and health cannot be configured, this is a limitation imposed by Forge (configs are loaded after entity attributes are already created).
