### ISSUE TITLE
[Crash]: Creeper Egg crash due to spamming right click on it to mount and dismount java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Lerrycapetime** [Fuzss/mutantmonsters#54]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1-47.2.1

### Mod Version (Required)

MutantMonsters-v8.0.4-1.20.1-Forge

### Notes (Required)

If you spam shift and right click the creeper egg it'll softlock and crash the game.

[crash-2023-10-22_20.12.21-server.txt](https://github.com/Fuzss/mutantmonsters/files/13065771/crash-2023-10-22_20.12.21-server.txt)

### Crash Report (Required)

[crash-2023-10-22_20.12.21-server.txt](https://github.com/Fuzss/mutantmonsters/files/13065771/crash-2023-10-22_20.12.21-server.txt)

**Comment by Fuzss** [comment]
Fixed in v8.0.5.

**Comment by Lerrycapetime** [comment]
Thanks so much!
