### ISSUE TITLE
[Suggestion]: Make items acquired from right clicking mutant skeleton parts be determined by loot tables

### ISSUE THREAD

**Issue by saltyseadoggo** [Fuzss/mutantmonsters#6]
### Suggestion (Required)

It would be helpful for modpack devs if the items a player gains by right clicking the parts the mutant skeleton drops upon death were determine by a loot table instead of being hardcoded.
For example, one could make the parts only have a chance to drop their respective items, and only drop bones the rest of the time, to make the armor require multiple mutant kills to get, or one could just make them not drop their respective items at all to prevent the armor set from being obtained completely.
I'd imagine this would be implemented by just having a loot table for each skeleton part entity- head, limb, rib, pelvis and shoulder pad- that by default just contains a 100% chance of dropping the respective item.~

**Comment by Fuzss** [comment]
Thanks for the suggestion! Added in v4.0.2.
