### ISSUE TITLE
[Bug]: Naturally generated mobs don't despawn

### ISSUE THREAD

**Issue by f0rttnite** [Fuzss/mutantmonsters#7]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

Mutant mobs that are spawned naturally don't seem to despawn, leading to situations where mutant zombies or skeletons can block you out from reaching dropped items should you die near them

**Comment by Fuzss** [comment]
Can’t reproduce either, maybe you were still too close.
