### ISSUE TITLE
[Crash]: Equipping Mutant Skeleton Armor causes crash

### ISSUE THREAD

**Issue by CCrown04** [Fuzss/mutantmonsters#71]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.6

### Minimal Setup

Yes

### Notes (Required)

Equip Mutant Skeleton Armor

### Crash Report (Required)

https://paste.gemwire.uk/view/c5f37926

**Comment by Fuzss** [comment]
This has nothing to do with Mutant Monsters.
https://github.com/emilyploszaj/chime/issues/37
