### ISSUE TITLE
[Bug]:  the mod now working and the mobs are normal not 

### ISSUE THREAD

**Issue by solomo12** [Fuzss/mutantmonsters#79]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.1

### Minimal Setup (Required)

Yes

### Notes (Required)

![image](https://github.com/Fuzss/mutantmonsters/assets/169847726/a5f96dad-7609-4e25-a4ee-1aa7e65832b3)
![image](https://github.com/Fuzss/mutantmonsters/assets/169847726/f2090c82-79bb-4154-aae8-4a42b7624c3a)
![image](https://github.com/Fuzss/mutantmonsters/assets/169847726/b619ba6b-9a24-4337-97a0-5b5de09869f3)
is not working and i download all libs

### latest.log (Required)

i dont have ERROR CODE

**Comment by Fuzss** [comment]
Mutants spawn rarely in addition to the vanilla monsters.
