### ISSUE TITLE
[Bug]: Mutant skeleton armor pieces are missing from Forge armor tags

### ISSUE THREAD

**Issue by saltyseadoggo** [Fuzss/mutantmonsters#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

The mutant skeleton skull, chestplate, leggings and boots are missing from `#forge:armors/helmets`, `#forge:armors/chestplates`, `#forge:armors/leggings` and `#forge:armors/boots`, respectively. This prevents them from working with certain features in other mods, such as Twilight Forest's equipment recrafting feature.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.2.
